---
defaults: &defaults
  adapter: mysql
  username: root
  password: password
  host:     localhost

development:
  database: registrame_development
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: registrame_test
  <<: *defaults
production:
  database: registrame_production
  <<: *defaults
